services:
  - type: web
    name: iframe-squares-gateway
    runtime: static
    buildCommand: bun install && bun run build
    staticPublishPath: ./dist
    pullRequestPreviewsEnabled: true
    envVars:
      - key: BUN_VERSION
        value: "1.0.15"
    headers:
      - path: /*
        name: Cache-Control
        value: no-cache
